apiVersion: apps/v1
kind: Deployment
metadata:
  name: lex-orion
  labels:
    app: lex-orion

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: lex-orion

  template:
    metadata:
      labels:
        app: lex-orion

    spec:
      containers:
        - name: lex-orion

          image: lex-orion:task3-v1

          imagePullPolicy: Never

          ports:
            - containerPort: 8501
              name: http

          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lex-orion-secrets
                  key: GROQ_API_KEY
                  optional: true

          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 768Mi